### ISSUE TITLE
Filtrer les mails que nous, Admins, on reçoit.

### ISSUE THREAD

**Issue by clairezed** [betagouv/place-des-entreprises#1548]
Il faut qu'on reçoivent que les commentaires des experts.
Les mails de confirmation d'envoi, de prise en charge et de clôture : “ pas joignable” “pas d’aide dispo” ou “aide proposé”, on ne veut pas les recevoir car pas d'action à faire.
_Tibo_

**Comment by clairezed** [comment]
@Tibo-aplus j'ai fait en sorte que les mails : 
```
Place des Entreprises] Des nouvelles de l’entreprise Bidule Chouette

Le besoin de l’entreprise Etablissements Bidule Chouette que vous avez adressé le 17 juin 2020 - xxxx - a évolué
```

ne vous soit plus adressé.

Il y avait d'autres mails ? 
Si oui, je veux bien que tu me donnes les intitulés, pour les retrouver

**Comment by Tibo-aplus** [comment]
non j'ai rien d'autre en tête, si ça me viens je referai une carte :) 

Cordialement, 



—

> Thibault Desjardins

> • Chargé de déploiement - Place des entreprises 
> • Twitter @BetaGouv – Incubateur de Services Numériques 
> • Start-up d'Etat - beta.gouv.fr
> • thibault.desjardins@beta.gouv.fr – +33 (0)6.22.99.03.65

--- original message ---
On February 8, 2021, 11:42 AM GMT+1 notifications@github.com wrote:



@Tibo-aplus j'ai fait en sorte que les mails :

Place des Entreprises] Des nouvelles de l’entreprise Bidule Chouette

Le besoin de l’entreprise Etablissements Bidule Chouette que vous avez adressé le 17 juin 2020 - xxxx - a évolué

ne vous soit plus adressé.

Il y avait d'autres mails ?

Si oui, je veux bien que tu me donnes les intitulés, pour les retrouver

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
